server:
  port: 3001
  error:
    include-stacktrace: never

eureka:
 client:
   enabled: false

#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: webfs
#      username: webfs
#      password: webfs


webfs:
  startDir: ${START_DIR:C:/}

logging.level.net.sf.corn.cps: OFF
logging.level.sun.net.www.protocol.jar: OFF
